services:
  vote:
    build:
      context: ./vote
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - ./vote:/usr/local/app
    ports:
      - "8080:80"
    environment:
      - REDIS_HOST=172.20.0.2
    networks:
      - front-tier
      - backend-voting-app_back-tier

  result:
    build: ./result
    volumes:
      - ./result:/usr/local/app
    ports:
      - "8081:80"
      - "127.0.0.1:9229:9229"
    environment:
      - DB_HOST=172.20.0.3
    networks:
      - front-tier
      - backend-voting-app_back-tier

networks:
  front-tier:
  backend-voting-app_back-tier:
    external: true
